apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostAliases:
      - ip: "10.48.0.11"
        hostnames:
        - "s048.048.pfr.ru"
        - "mail.048.pfr.ru"
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
