apiVersion: v1
kind: Service
metadata:
  labels:
    run: node-hello-world 
  name: node-hello-world 
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: node-hello-world 
  sessionAffinity: None
  type: ClusterIP
status:
